In [2]:
import numpy as np

a = np.arange(10, 20, 2)
print(a)

# slicing just until n-1 ===> pay attention to it
print("Slicing")
print("\n a[:] =", a[:])
print("\n a[0:2] =", a[0:2])
print("\n a[:3] =", a[:3])
print("\n a[3:] =", a[3:])
print("\n a[-3:-1] =", a[-3:-1])

[10 12 14 16 18]
Slicing

 a[:] = [10 12 14 16 18]

 a[0:2] = [10 12]

 a[:3] = [10 12 14]

 a[3:] = [16 18]

 a[-3:-1] = [14 16]


In [4]:
# slicing the multidementionl array
b = np.arange(20)
b.resize(4, 6)
print(b)

# slicing just until n-1 ===> pay attention to it
print("Slicing")
print("\n b[0] =", b[0])
print("\n b[0:2] =", b[0:2])
print("\n b[0:2, 0:2] =", b[0:2, 0:2])
print("\n b[2:, 4:] =", b[2:, 4:])




[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19  0  0  0  0]]
Slicing

 b[0] = [0 1 2 3 4 5]

 b[0:2] = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 b[0:2, 0:2] = [[0 1]
 [6 7]]

 b[2:, 4:] = [[16 17]
 [ 0  0]]


In [5]:
a = np.array([1, 2, 3, 45])

print("Array datatype is {}".format(a.dtype))

print("Memory size of one array element is {} byte(s)".format(a.itemsize))

print("Total memory size of array is {} byte(s)".format(a.size * a.itemsize))

# we can use nbytes also to get the information about total memory size 
print("Total memory size of array is {} byte(s)".format(a.nbytes))

Array datatype is int32
Memory size of one array element is 4 byte(s)
Total memory size of array is 16 byte(s)
Total memory size of array is 16 byte(s)


In [7]:
# the default dtype is 32
# default for float is 64
a = np.array([1, 2, 3, 45], dtype='int')
print("Array:", a, "\nDataType:", a.dtype)
b = np.array([1, 2, 3, 45], dtype='float')
print("Array:", b, "\nDataType:", b.dtype)

Array: [ 1  2  3 45] 
DataType: int32
Array: [ 1.  2.  3. 45.] 
DataType: float64


In [4]:
a = np.array([1, 2, 3, 45], dtype='int16')
print("Array:", a, "\nDataType:", a.dtype)

Array: [ 1  2  3 45] 
DataType: int16


In [5]:
# i2 is equvalent to int16, f2 ==> float16
a = np.array([1, 2, 3, 45], dtype='i2')
print("Array:", a, "\nDataType:", a.dtype)

Array: [ 1  2  3 45] 
DataType: int16


In [8]:
# data type for boolean
b = np.array([True, False, True], dtype='bool')
print("Array:", b, "\nDataType:", b.dtype)

# example 2
b = np.array([True, False, True], dtype='?')
print("Array:", b, "\nDataType:", b.dtype)



Array: [ True False  True] 
DataType: bool
Array: [ True False  True] 
DataType: bool


In [9]:
b = np.array(["Python", "Numpy", "Pandas"], dtype='S')
print("Array: ", b, "\nDataType", b.dtype)

Array:  [b'Python' b'Numpy' b'Pandas'] 
DataType |S6


In [10]:
b = np.array(["Python", "Numpy", "Pandas"], dtype='U')
print("Array: ", b, "\nDataType", b.dtype)

Array:  ['Python' 'Numpy' 'Pandas'] 
DataType <U6


In [14]:
# ???????????????
import numpy as np
employee = np.dtype([('name', 'S10'), ('dept', 'S10'), ('sal', '14')])
print("Structured Data Type:", employee)

emp_array = np.array([('Jim', 'HR', 7000), ("Mark", 'IT', 8000), ('Allen', 'Admin', 10000)], dtype=employee)
print("\nArray: ", emp_array, "\nDataType:", emp_array.dtype)

TypeError: data type '' not understood