In [2]:
# 1-D array
import numpy as np
num_array = np.array([1, 2, 3, 45, 6])
print(num_array)

new_num_array = np.append(num_array,[10])
print(new_num_array)

[ 1  2  3 45  6]
[ 1  2  3 45  6 10]


In [6]:
# 2-D array
a = np.array([[1, 2, 3],[4, 5, 6]])
print(f'\nExisiting Array\n', a)

a1 = np.append(a, [7, 8, 9])
print(f'\n new array without axis\n', a1)

a2 = np.append(a, [[7, 8, 9]], axis=0)
print(f'\n new array with axis\n', a2)

a3 = np.append(a, [[0], [1]], axis=1)
print(f'\n new array with axis\n', a3)


Exisiting Array
 [[1 2 3]
 [4 5 6]]

 new array without axis
 [1 2 3 4 5 6 7 8 9]

 new array with axis
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 new array with axis
 [[1 2 3 0]
 [4 5 6 1]]


In [8]:
# inserting a new element in exsiting array 
# np.insert(existing_array, index, value)
num_array = np.array([1, 2, 3, 45, 6])
print('\n Existing Array:\n', num_array)
new_num_array = np.insert(num_array,1, [10])
print('\n new array with inserted element:\n', new_num_array)


 Existing Array:
 [ 1  2  3 45  6]

 new array with inserted element:
 [ 1 10  2  3 45  6]


In [10]:
# deleting an element in existing array
# np.delete(ndarray, index)

num_array = np.array([1, 2, 3, 45, 6])
print('\n Existing Array:\n', num_array)

new_num_array = np.delete(num_array, 1)
print('\n new array with de element:\n', new_num_array)


 Existing Array:
 [ 1  2  3 45  6]

 new array with de element:
 [ 1  3 45  6]


In [12]:
# input arrays 
array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])
print('\n first array:\n', array_1)
print('\n second array:\n', array_2)

# row wise 
array_concat = np.concatenate((array_1, array_2))
print('\n concated array with default axis\n', array_concat)

# column wise
array_concat = np.concatenate((array_1, array_2), axis=1)
print('\n concated array with default axis\n', array_concat)


 first array:
 [[1 2]
 [3 4]]

 second array:
 [[5 6]
 [7 8]]

 concated array with default axis
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 concated array with default axis
 [[1 2 5 6]
 [3 4 7 8]]


In [13]:
# np.hstack(): stack the arrays horizontly like concat with axis=1
array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])
print('\n first array:\n', array_1)
print('\n second array:\n', array_2)

array_hstacked = np.hstack((array_1, array_2))
print('\n concated array with hstack() :\n', array_hstacked)



 first array:
 [[1 2]
 [3 4]]

 second array:
 [[5 6]
 [7 8]]

 concated array with hstack() :
 [[1 2 5 6]
 [3 4 7 8]]


In [14]:
# np.vstack() : stack the arrays vertically like concat with axis=0

# row wise

array_1 = np.array([[1, 2], [3, 4]])
array_2 = np.array([[5, 6], [7, 8]])
print('\n first array:\n', array_1)
print('\n second array:\n', array_2)

array_vstacked = np.vstack((array_1, array_2))
print('\n Concated array with vstack() :\n', array_vstacked)


 first array:
 [[1 2]
 [3 4]]

 second array:
 [[5 6]
 [7 8]]

 Concated array with vstack() :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print('\n Input array before split\n', a)

print("\n output array after split()\n", np.split(a, 4))
print("\n output array after split()\n", np.split(a, 2))


 Input array before split
 [1 2 3 4 5 6 7 8]

 output array after split()
 [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

 output array after split()
 [array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [16]:
array_input = np.array([(1, 2, 3, 4), (6, 7, 8, 9)])
array_1, array_2 = np.hsplit(array_input, 2)

print('\n Input array before split\n', array_input)
print("\n output  horizental array 1\n", array_1)
print("\n output  horizental array 2)\n", array_2)


 Input array before split
 [[1 2 3 4]
 [6 7 8 9]]

 output  horizental array 1
 [[1 2]
 [6 7]]

 output  horizental array 2)
 [[3 4]
 [8 9]]


In [17]:
array_input = np.array([(1, 2, 3, 4, 10, 11), (6, 7, 8, 9, 10, 11)])
array_1, array_2 = np.vsplit(array_input, 2)
print('\n Input array before split\n', array_input)
print("\n output vertical  array 1\n", array_1)
print("\n output  vertical array 2)\n", array_2)


 Input array before split
 [[ 1  2  3  4 10 11]
 [ 6  7  8  9 10 11]]

 output vertical  array 1
 [[ 1  2  3  4 10 11]]

 output  vertical array 2)
 [[ 6  7  8  9 10 11]]
