In [4]:
import numpy as np
arr1 = np.arange(12, dtype = np.float_).reshape(3, 4)
arr2 = np.array([[1, 2, 3, 4]], dtype = np.float_)

print("First array -arr1: \n", arr1)
print("second array - arr2 \n", arr2)

result_add = np.add(arr1, arr2)
result_subtract = np.subtract(arr1, arr2)
result_multiply = np.multiply(arr1, arr2)
result_divide = np.divide(arr1, arr2)
print("##############")
print(result_add)
print("##############")
print(result_subtract)
print("##############")
print(result_multiply)
print("##############")
print(result_divide)

First array -arr1: 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
second array - arr2 
 [[1. 2. 3. 4.]]
##############
[[ 1.  3.  5.  7.]
 [ 5.  7.  9. 11.]
 [ 9. 11. 13. 15.]]
##############
[[-1. -1. -1. -1.]
 [ 3.  3.  3.  3.]
 [ 7.  7.  7.  7.]]
##############
[[ 0.  2.  6. 12.]
 [ 4. 10. 18. 28.]
 [ 8. 18. 30. 44.]]
##############
[[0.         0.5        0.66666667 0.75      ]
 [4.         2.5        2.         1.75      ]
 [8.         4.5        3.33333333 2.75      ]]


In [5]:
# numpy power 

power_2_array = np.power(arr1, 2)
print("Output array :\n", power_2_array)

Output array :
 [[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]]


In [8]:
# the mod function returns the reminder of the division between two arrays corresponding to the elements of both the arrays.

arr1 = np.array([10, 23, 21, 11])
arr2 = np.array([1, 2, 3, 4])

print(arr1)
print(arr2)

out_arr = np.mod(arr1, arr2)
print("Output array after mod\n", out_arr)

[10 23 21 11]
[1 2 3 4]
Output array after mod
 [0 1 0 3]


In [9]:
input_arr1 = np.array([[0.5, 3, 0.8], [4, 1, 7]])
input_arr2 = np.array([[2, 3, 4], [4, 1, 7]])

# example when array types is float
print("input array:\n", input_arr1)
print("Reciprocal of arr1:\n", np.reciprocal(input_arr1))

# example when array type is int
print("input array:\n", input_arr2)
print("Reciprocal of arr1:\n", np.reciprocal(input_arr2))

input array:
 [[0.5 3.  0.8]
 [4.  1.  7. ]]
Reciprocal of arr1:
 [[2.         0.33333333 1.25      ]
 [0.25       1.         0.14285714]]
input array:
 [[2 3 4]
 [4 1 7]]
Reciprocal of arr1:
 [[0 0 0]
 [0 1 0]]
