In [1]:
import numpy as np
array1_1D = np.array([1, 2, 3, 4, 5])
array2_1D = np.array((2, 3, 4, 5))
print(array1_1D)
print(array2_1D)


[1 2 3 4 5]
[2 3 4 5]


In [2]:
# make the 2domensial array
array3_2D = np.array([(1, 3, 5), (2, 4, 6)])

print(array3_1D)

[[1 3 5]
 [2 4 6]]


In [3]:
# make the complex array
array1_1D_complex = np.array([1, 3, 5], dtype='complex')
print(array1_1D_complex)

[1.+0.j 3.+0.j 5.+0.j]


In [5]:
# array with zeros
array_zeros = np.zeros((2, 3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# array with ones
array_ones = np.ones((3, 4))
print(type(array_ones))
array_ones

<class 'numpy.ndarray'>


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# empty function ===> return the array with random values
array_empty = np.empty((3, 3))
array_empty

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.07502005e-321],
       [8.45603440e-307, 4.45046007e-307, 2.37667058e-312]])

In [10]:
# creating array with python list
t1 = [1, 2, 4]
print(np.asarray(t1, dtype='int16'))


[1 2 4]


In [17]:

t2 = [[1, 2, 3], [2, 3, 4]]
t2_array = np.asarray(t2, dtype='int16')
print(type(t2_array))
print(t2_array)
t2_array

# if we use print for show our array the oupt doesn't have a comma, but if we just use the variable our output has an comma.

<class 'numpy.ndarray'>
[[1 2 3]
 [2 3 4]]


array([[1, 2, 3],
       [2, 3, 4]], dtype=int16)

In [19]:
# using the tuple
t1 = ((1, 2, 4))
print(np.asarray(t1, dtype='int16'))

[1 2 4]


In [21]:
t2 = ((1, 2, 3), (2, 3, 4))
t2_array = np.asarray(t2, dtype='int16')
t2_array

array([[1, 2, 3],
       [2, 3, 4]], dtype=int16)

In [22]:
# creating array using arange() function
# np.arrange(start, stop, step, dtype)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [23]:
import numpy as np
a = np.array([1, 2, 3, 45,], dtype='int')
print("Array : ", a, "\nDataType:", a.dtype)

Array :  [ 1  2  3 45] 
DataType: int32
