In [10]:
import numpy as np 
num_array = np.arange(2, 10, 2)

# reshape 
array_shape = num_array.reshape(2, 2)
print("\n before reshape:\n", num_array)
print("after applying reshape(2, 2)\n", array_shape)

#use of flat 
array_flat = array_shape.flat[3]
print("\n before apply flat:\n", num_array)
print("after applying flat[3]\n", array_flat)

# use of flatten()
array_flatten = array_shape.flatten()
print("\n before apply flatten:\n", array_shape)
print("after applying flatten\n", array_flatten)

# use of ravel()
array_ravel = array_shape.ravel()
print("\n before apply ravel:\n", array_shape)
print("after applying ravel\n", array_ravel)


# use of transpose(), transpose the axes
array_transpose = array_shape.transpose()
print("\n before apply transpose:\n", array_shape)
print("after applying transpose\n", array_transpose)

# use of resize()
a = np.arange(2, 20, 2)
print("\n before apply resize:\n", a)
a.resize((5, 4))
print("\n output after applying the resize\n", a)


 before reshape:
 [2 4 6 8]
after applying reshape(2, 2)
 [[2 4]
 [6 8]]

 before apply flat:
 [2 4 6 8]
after applying flat[3]
 8

 before apply flatten:
 [[2 4]
 [6 8]]
after applying flatten
 [2 4 6 8]

 before apply ravel:
 [[2 4]
 [6 8]]
after applying ravel
 [2 4 6 8]

 before apply transpose:
 [[2 4]
 [6 8]]
after applying transpose
 [[2 6]
 [4 8]]

 before apply resize:
 [ 2  4  6  8 10 12 14 16 18]

 output after applying the resize
 [[ 2  4  6  8]
 [10 12 14 16]
 [18  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
