In [1]:
import numpy as np

a = np.array([[11, 14], [13, 11]])
print("input array is :\n", a)

out1 = np.sort(a)
print("\n output sorted array when no axis defined means default axis:\n", out1)

# sort the flattened array
out2 = np.sort(a, axis=None)
print("\n output sorted array when axis=None:\n", out2)

out3 = np.sort(a, axis=0)
print("\n output sorted array when axis=None:\n", out3)

input array is :
 [[11 14]
 [13 11]]

 output sorted array when no axis defined means default axis:
 [[11 14]
 [11 13]]

 output sorted array when axis=None:
 [11 11 13 14]

 output sorted array when axis=None:
 [[11 11]
 [13 14]]
