In [3]:
import numpy as np
a = np.array([[23, 45, 11], [20, 98, 43], [20, 65, 33]])
print('input array :\n', a)

# numpy.amin() - returns the minimum element from array 
a_min = np.amin(a)
print('minimum value ', a_min)

# numpy.amin() - returns the maximum element from array 
a_max = np.amax(a)
print('maximum value', a_max)

a_min_0 = np.amin(a, axis=0)
print('minimum value along axis=0', a_min_0)

a_min_1 = np.amin(a, axis=1)
print('minimum value along axis=1', a_min_1)

a_max_0 = np.amax(a, axis=0)
print('maximum value along axis=0', a_max_0)

a_max_1 = np.amax(a, axis=1)
print('maximum value along axis=1', a_max_1)




input array :
 [[23 45 11]
 [20 98 43]
 [20 65 33]]
minimum value  11
maximum value 98
minimum value along axis=0 [20 45 11]
minimum value along axis=1 [11 20 20]
maximum value along axis=0 [23 98 43]
maximum value along axis=1 [45 98 65]


In [4]:
a = np.array([23, 45, 11])
print('Input array a:\n', a)
print("mean value of the input array:", np.mean(a))

Input array a:
 [23 45 11]
mean value of the input array: 26.333333333333332


In [5]:
print("\n average() without weights:", np.average(a))

wt_arr = np.array([0.5, 2, 3])
print("\n average with weights:", np.average(a, weights=wt_arr))


 average() without weights: 26.333333333333332

 average with weights: 24.454545454545453


In [11]:
input_arr = np.array([23, 45, 11, 3, 1])
print("input array a:\n", input_arr)
print("\n Median value of the input array:", np.median(input_arr))

input array a:
 [23 45 11  3  1]

 Median value of the input array: 11.0


In [12]:
# numpy std() return the deviation(انحراف از معیار)
print("\n standard division of the given data:", np.std(input_arr))


 standard division of the given data: 16.169106345126192


In [13]:
# numpy return variance of the given array : numpy.var():
input_arr = np.array([23, 45, 11, 3, 1])
print("input array a:\n", input_arr)
print("\n Variance of the give data:", np.var(input_arr))

input array a:
 [23 45 11  3  1]

 Variance of the give data: 261.44000000000005


In [14]:
input_arr = [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [3, 4, 5, 6]]

print("input array a:\n", input_arr)

# percentile when axis=None
print("\n 25th Percentile of input_arr, axis=None", np.percentile(input_arr, 25))

# percentile when axis=0
print("\n 25th Percentile of input_arr, axis=None", np.percentile(input_arr, 25, axis=0))

# percentile when axis=1
print("\n 25th Percentile of input_arr, axis=None", np.percentile(input_arr, 25, axis=1))


input array a:
 [[1, 2, 3, 4], [5, 6, 7, 8], [3, 4, 5, 6]]

 25th Percentile of input_arr, axis=None 3.0

 25th Percentile of input_arr, axis=None [2. 3. 4. 5.]

 25th Percentile of input_arr, axis=None [1.75 5.75 3.75]
